module.exports = {
  APPOINTMENT_RECEIVED: 'APPOINTMENT_RECEIVED',
  APPOINTMENT_REMOVED: 'APPOINTMENT_REMOVED',
  APPOINTMENTS_RECEIVED: 'APPOINTMENTS_RECEIVED',
  ERROR_RECEIVED: 'ERROR_RECEIVED'
};
